---
- name: Create a virtual machine a vCenter
  community.vmware.vmware_guest:
    hostname: "{{ vmware.host }}"
    username: "{{ vmware.username }}"
    password: "{{ vmware.password }}"
    cluster: "{{ cluster_name }}"
    folder: "{{ folder_path }}"
    name: "{{ vm_name }}"
    datacenter: "{{ datacenter_name }}"
    datastore: "{{ datastore_name }}"
    state: present
    guest_id: "{{ vm_hardware }}"
    template: "{{ template }}"
    disk:
      - size_gb: "{{ disk_size }}"
        type: thin
        datastore: "{{ datastore_name }}"
    hardware:
      memory_mb: "{{ mem_size }}"
      num_cpus: "{{ num_cpu }}"
      scsi: paravirtual
    networks:
      - name: "{{ network_name }}"
        type: "dhcp"
        device_type: vmxnet3
    wait_for_ip_address: true
    wait_for_ip_address_timeout: 60
  delegate_to: localhost
  register: deploy_vm

- name: Enforce primary NIC is online
  community.vmware.vmware_guest_network:
    hostname: "{{ vmware.host }}"
    username: "{{ vmware.username }}"
    password: "{{ vmware.password }}"
    moid: "{{ deploy_vm.instance.moid }}"
    mac_address: "{{ deploy_vm.instance.hw_eth0.macaddress }}"
    state: present
    start_connected: true
    connected: true
